# Generated by Django 4.0.4 on 2022-06-08 11:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('\\D+', message='Че ты делаешь?')], verbose_name='Имя автора')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Возраст')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта')),
                ('lit_type', models.CharField(choices=[('а', 'Зарубежная'), ('б', 'Фантастика'), ('в', 'Фэнтези')], default='a', max_length=50, verbose_name='Жанр литературы')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'ordering': ('name', 'age'),
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название книги')),
                ('description', models.TextField()),
                ('amount_pages', models.IntegerField()),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_lib.author')),
            ],
            options={
                'get_latest_by': 'published',
            },
        ),
    ]
