# Generated by Django 4.0.4 on 2022-06-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, null=True)),
                ('cost', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('size', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Размер')),
                ('cost', models.IntegerField(null=True, verbose_name='Цена')),
                ('addr', models.CharField(default='Грозный', max_length=200, verbose_name='Адрес')),
                ('bal', models.BooleanField(default=True, verbose_name='Балкон')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, null=True)),
                ('cost', models.CharField(max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
        ),
    ]
